export enum UserActionTypes {
    GET_PROFILE = "GET_PROFILE",
    REGISTER_USER = "REGISTER_USER",
    REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAILED = "REGISTER_USER_FAILED",
}
