export const GET_NFT_DATA_REQUEST = "GET_NFT_DATA_REQUEST";
export const GET_NFT_DATA_REQUEST_SUCCESS = "GET_NFT_DATA_REQUEST_SUCCESS";
export const GET_NFT_DATA_REQUEST_FAILED = "GET_NFT_DATA_REQUEST_FAILED";
